---
title: Services
description: Configures services.
actions:
  - !writeStatus: {status: 'Configuring services'}
  - !powerShell:
    command: '.\Astro\filesharing.ps1'
    exeDir: true
    wait: true
  - !service: {name: 'OneSyncSvc', operation: change, startup: 4}
  - !service: {name: 'TrkWks', operation: change, startup: 4}
  - !service: {name: 'PcaSvc', operation: change, startup: 4}
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
  - !service: {name: 'diagnosticshub.standardcollector.service', operation: change, startup: 4}
  - !service: {name: 'WerSvc', operation: change, startup: 4} 
  - !service: {name: 'wercplsupport', operation: change, startup: 4}
  - !service: {name: 'UCPD', operation: change, startup: 4}
  - !service: {name: 'GpuEnergyDrv', operation: change, startup: 4}
  - !service: {name: 'NetBT', operation: change, startup: 4}
  - !service: {name: 'Telemetry', operation: change, startup: 4}